"""NVIDIA OpenShell export: derive a sandbox policy (version 1 schema) from an agent's tool allowlist.

agentkit is the harness (what the agent TRIES: tools, approvals, budgets). OpenShell is the runtime below it
(what the agent CAN do: Landlock filesystem, seccomp, proxy-enforced egress, routed inference, credential
injection). The export is deny-by-default: only hosts a tool actually needs are allowed, model calls go
through `inference.local`, and approval-gated actions (email) are NOT pre-authorized — they are added as a
narrow rule only when the owner approves. A child agent's policy is always a subset of its builder's."""
from __future__ import annotations

import os
from pathlib import Path

from .config import Config

PY = "/usr/bin/python3"
PY_BINARIES = [{"path": PY}, {"path": "/usr/local/bin/python3.12"}]  # distro python, and the python:3.12-slim image's real binary

# hosts each tool needs; anything else is denied by the sandbox proxy
TOOL_HOSTS = {
    "web_search": [("html.duckduckgo.com", 443, "read-only"), ("duckduckgo.com", 443, "read-only"), ("lite.duckduckgo.com", 443, "read-only")],
    # web_fetch reaches arbitrary public pages: intentionally NOT pre-allowed. OpenShell's policy-advisor loop turns each
    # L4 denial into a pending rule the owner approves (same posture as this harness: propose, then approve).
    "web_fetch": [],
}
APPROVAL_HOSTS = {"send_email": "SMTP host (from SMTP_HOST) — add a rule only when a send_email approval is executed"}


def policy_for(cfg: Config, l7: str | None = None) -> dict:
    """`l7` is the L7 protocol name for HTTPS endpoints: `rest` for current OpenShell (>= 0.0.37), `https` for the 0.0.1x schema.
    Default from AGENTKIT_OPENSHELL_L7, else `rest`."""
    l7 = l7 or os.environ.get("AGENTKIT_OPENSHELL_L7", "rest")
    endpoints: dict[str, dict] = {}
    for tool in cfg.tools_allowed:
        for host, port, access in TOOL_HOSTS.get(tool, []):
            endpoints.setdefault(host, {"host": host, "port": port, "protocol": l7, "enforcement": "enforce", "access": access})
    return {
        "version": 1,
        "filesystem_policy": {
            "include_workdir": True,
            "read_only": ["/usr", "/lib", "/proc", "/dev/urandom", "/app", "/etc", "/var/log"],
            "read_write": ["/sandbox", "/sandbox/data", "/sandbox/reports", "/tmp", "/dev/null"],
        },
        "landlock": {"compatibility": "best_effort"},
        "network_policies": ({"tool_egress": {"name": f"{cfg.agent.slug}-tool-egress", "endpoints": list(endpoints.values()),
                                              "binaries": list(PY_BINARIES)}} if endpoints else {}),
        "_derived_from": {"agent": cfg.agent.slug, "tools": list(cfg.tools_allowed), "approval_actions": list(cfg.approval_actions),
                          "not_preauthorized": {a: APPROVAL_HOSTS[a] for a in cfg.approval_actions if a in APPROVAL_HOSTS}},
    }


def to_yaml(policy: dict) -> str:
    """Minimal YAML writer for this fixed shape (no PyYAML dependency)."""
    L = [f"# OpenShell sandbox policy for {policy['_derived_from']['agent']} — generated by agentkit from the tool allowlist.",
         f"# tools: {', '.join(policy['_derived_from']['tools']) or 'none'}",
         f"# approval actions (NOT pre-authorized): {', '.join(policy['_derived_from']['approval_actions']) or 'none'}"]
    for a, why in policy["_derived_from"]["not_preauthorized"].items():
        L.append(f"#   {a}: {why}")
    L += ["# Model calls route through https://inference.local (set with `openshell inference set`); caller keys are stripped.", "",
          "version: 1", "", "filesystem_policy:", f"  include_workdir: {'true' if policy['filesystem_policy']['include_workdir'] else 'false'}",
          f"  read_only: [{', '.join(policy['filesystem_policy']['read_only'])}]",
          f"  read_write: [{', '.join(policy['filesystem_policy']['read_write'])}]",
          "landlock:", f"  compatibility: {policy['landlock']['compatibility']}", ""]
    if policy["network_policies"]:
        L.append("network_policies:")
        for key, blk in policy["network_policies"].items():
            L += [f"  {key}:", f"    name: {blk['name']}", "    endpoints:"]
            for e in blk["endpoints"]:
                L.append(f"      - host: {e['host']}")
                L.append(f"        port: {e['port']}")
                L.append(f"        protocol: {e['protocol']}")
                L.append(f"        enforcement: {e['enforcement']}")
                L.append(f"        access: {e['access']}")
            L.append("    binaries:")
            for b in blk["binaries"]:
                L.append(f"      - {{ path: {b['path']} }}")
    else:
        L.append("network_policies: {}   # no tool needs egress; only routed inference leaves the sandbox")
    return "\n".join(L) + "\n"


def launch_doc(cfg: Config) -> str:
    return f"""# Run {cfg.agent.name} under NVIDIA OpenShell

OpenShell is the runtime below this harness: it enforces what the agent CAN do (Landlock, seccomp, proxy egress,
routed inference, injected credentials) while agentkit governs what it TRIES (tools, approvals, budgets).
Host: Linux, macOS (Apple Silicon), or Windows with WSL 2. Install: `curl -LsSf https://raw.githubusercontent.com/NVIDIA/OpenShell/main/install.sh | sh`

Verified 2026-09-02 on an NVIDIA DGX Spark (Ubuntu 24.04, aarch64) with OpenShell 0.0.16 and a host-level Ollama.

```bash
openshell gateway start                                   # local k3s-in-docker gateway (first run pulls the cluster image)

# 1. a provider for the model backend; credentials never enter the sandbox filesystem (injected as env vars at creation)
#    host-level Ollama / vLLM / NIM (OpenAI-compatible):
openshell provider create --name ollama --type openai --credential OPENAI_API_KEY=empty \\
  --config OPENAI_BASE_URL=http://host.openshell.internal:11434/v1
#    or NVIDIA cloud:  openshell provider create --name nvidia --type nvidia --credential NVIDIA_API_KEY

# 2. route this agent's model calls through the gateway (caller-supplied keys are stripped, backend keys injected)
openshell inference set --provider ollama --model {cfg.model.openai_model}

# 3. build the sandbox image from the repo Dockerfile (python:3.12-slim + iproute2; MUST contain user+group `sandbox`),
#    apply the derived policy, attach the provider, start Mission Control inside the sandbox
openshell sandbox create --name {cfg.agent.slug} --from ./Dockerfile --policy {cfg.root.name}/openshell/policy.yaml \\
  --provider ollama --no-tty -- python3 -m agentkit --root /sandbox/{cfg.root.name} mc

# 4. reach it from the host, watch the proxy enforce the policy, review advisor-proposed rules
openshell forward start {cfg.mc_port} {cfg.agent.slug}          # then http://127.0.0.1:{cfg.mc_port}
openshell logs {cfg.agent.slug} --tail
openshell rule get --status pending

# 5. later policy changes (network / inference) hot-reload without restarting
openshell policy set {cfg.agent.slug} --policy {cfg.root.name}/openshell/policy.yaml --wait
```

In `agent.toml` set `[model].backend = "openai_compat"`, `openai_base_url = "https://inference.local/v1"`,
`openai_api_key_env = "OPENAI_API_KEY"` (the attached provider injects it) and `openai_model` to the routed model.
Approval-gated actions ({', '.join(cfg.approval_actions) or 'none'}) get their egress rule only when the owner approves,
so the sandbox cannot send even if the harness were bypassed. A built agent's policy is a subset of its builder's
(authority ceiling): the Foundry's own policy has no tool egress at all.
"""


def export(cfg: Config, dest: Path | None = None, l7: str | None = None) -> Path:
    out = Path(dest) if dest else cfg.root / "openshell"
    out.mkdir(parents=True, exist_ok=True)
    (out / "policy.yaml").write_text(to_yaml(policy_for(cfg, l7)), encoding="utf-8")
    (out / "RUN_UNDER_OPENSHELL.md").write_text(launch_doc(cfg), encoding="utf-8")
    return out
