"""NVIDIA OpenShell export: derive a sandbox policy (version 1 schema) from an agent's tool allowlist.

agentkit is the harness (what the agent TRIES: tools, approvals, budgets). OpenShell is the runtime below it
(what the agent CAN do: Landlock filesystem, seccomp, proxy-enforced egress, routed inference, credential
injection). The export is deny-by-default: only hosts a tool actually needs are allowed, model calls go
through `inference.local`, and approval-gated actions (email) are NOT pre-authorized — they are added as a
narrow rule only when the owner approves. A child agent's policy is always a subset of its builder's."""
from __future__ import annotations

from pathlib import Path

from .config import Config

PY = "/usr/bin/python3"

# hosts each tool needs; anything else is denied by the sandbox proxy
TOOL_HOSTS = {
    "web_search": [("html.duckduckgo.com", 443, "read-only"), ("duckduckgo.com", 443, "read-only"), ("lite.duckduckgo.com", 443, "read-only")],
    # web_fetch reaches arbitrary public pages: intentionally NOT pre-allowed. OpenShell's policy-advisor loop turns each
    # L4 denial into a pending rule the owner approves (same posture as this harness: propose, then approve).
    "web_fetch": [],
}
APPROVAL_HOSTS = {"send_email": "SMTP host (from SMTP_HOST) — add a rule only when a send_email approval is executed"}


def policy_for(cfg: Config) -> dict:
    endpoints: dict[str, dict] = {}
    for tool in cfg.tools_allowed:
        for host, port, access in TOOL_HOSTS.get(tool, []):
            endpoints.setdefault(host, {"host": host, "port": port, "protocol": "https", "enforcement": "enforce", "access": access})
    return {
        "version": 1,
        "filesystem_policy": {
            "include_workdir": True,
            "read_only": ["/usr", "/lib", "/proc", "/dev/urandom", "/app", "/etc", "/var/log"],
            "read_write": ["/sandbox", "/sandbox/data", "/sandbox/reports", "/tmp", "/dev/null"],
        },
        "landlock": {"compatibility": "best_effort"},
        "network_policies": ({"tool_egress": {"name": f"{cfg.agent.slug}-tool-egress", "endpoints": list(endpoints.values()),
                                              "binaries": [{"path": PY}]}} if endpoints else {}),
        "_derived_from": {"agent": cfg.agent.slug, "tools": list(cfg.tools_allowed), "approval_actions": list(cfg.approval_actions),
                          "not_preauthorized": {a: APPROVAL_HOSTS[a] for a in cfg.approval_actions if a in APPROVAL_HOSTS}},
    }


def to_yaml(policy: dict) -> str:
    """Minimal YAML writer for this fixed shape (no PyYAML dependency)."""
    L = [f"# OpenShell sandbox policy for {policy['_derived_from']['agent']} — generated by agentkit from the tool allowlist.",
         f"# tools: {', '.join(policy['_derived_from']['tools']) or 'none'}",
         f"# approval actions (NOT pre-authorized): {', '.join(policy['_derived_from']['approval_actions']) or 'none'}"]
    for a, why in policy["_derived_from"]["not_preauthorized"].items():
        L.append(f"#   {a}: {why}")
    L += ["# Model calls route through https://inference.local (set with `openshell inference set`); caller keys are stripped.", "",
          "version: 1", "", "filesystem_policy:", f"  include_workdir: {'true' if policy['filesystem_policy']['include_workdir'] else 'false'}",
          f"  read_only: [{', '.join(policy['filesystem_policy']['read_only'])}]",
          f"  read_write: [{', '.join(policy['filesystem_policy']['read_write'])}]",
          "landlock:", f"  compatibility: {policy['landlock']['compatibility']}", ""]
    if policy["network_policies"]:
        L.append("network_policies:")
        for key, blk in policy["network_policies"].items():
            L += [f"  {key}:", f"    name: {blk['name']}", "    endpoints:"]
            for e in blk["endpoints"]:
                L.append(f"      - host: {e['host']}")
                L.append(f"        port: {e['port']}")
                L.append(f"        protocol: {e['protocol']}")
                L.append(f"        enforcement: {e['enforcement']}")
                L.append(f"        access: {e['access']}")
            L.append("    binaries:")
            for b in blk["binaries"]:
                L.append(f"      - {{ path: {b['path']} }}")
    else:
        L.append("network_policies: {}   # no tool needs egress; only routed inference leaves the sandbox")
    return "\n".join(L) + "\n"


def launch_doc(cfg: Config) -> str:
    return f"""# Run {cfg.agent.name} under NVIDIA OpenShell

OpenShell is the runtime below this harness: it enforces what the agent CAN do (Landlock, seccomp, proxy egress,
routed inference, injected credentials) while agentkit governs what it TRIES (tools, approvals, budgets).
Host: Linux, macOS (Apple Silicon), or Windows with WSL 2. Install: `curl -LsSf https://raw.githubusercontent.com/NVIDIA/OpenShell/main/install.sh | sh`

```bash
# 1. credentials never enter the sandbox filesystem; they are injected as env vars at creation
openshell provider create --type generic --name {cfg.agent.slug}-model --from-existing   # e.g. NVIDIA_API_KEY

# 2. route this agent's model calls through the gateway (caller-supplied keys are stripped, backend keys injected)
openshell inference set --provider {cfg.agent.slug}-model --model {cfg.model.openai_model}

# 3. create the sandbox with the derived policy and start Mission Control inside it
openshell sandbox create {cfg.agent.slug} --policy openshell/policy.yaml -- \\
  env AGENTKIT_MODEL_BACKEND=openai_compat python3 -m agentkit --root /sandbox mc --port {cfg.mc_port}

# 4. later policy changes (network / inference) hot-reload without restarting
openshell policy set {cfg.agent.slug} --policy openshell/policy.yaml --wait
```

In `agent.toml`, point `[model].openai_base_url` at `https://inference.local/v1` when running under OpenShell.
Approval-gated actions ({', '.join(cfg.approval_actions) or 'none'}) get their egress rule only when the owner approves,
so the sandbox cannot send even if the harness were bypassed. A built agent's policy is a subset of its builder's
(authority ceiling): the Foundry's own policy has no tool egress at all.
"""


def export(cfg: Config, dest: Path | None = None) -> Path:
    out = Path(dest) if dest else cfg.root / "openshell"
    out.mkdir(parents=True, exist_ok=True)
    (out / "policy.yaml").write_text(to_yaml(policy_for(cfg)), encoding="utf-8")
    (out / "RUN_UNDER_OPENSHELL.md").write_text(launch_doc(cfg), encoding="utf-8")
    return out
