"""Agent Seller — generated by Agent Foundry. Runs on agentkit's generic worker; panels expose its records in Mission Control."""
from agentkit.worker import Worker  # noqa: F401  (generic task loop)

PANELS = [
    {
        "name": "Leads",
        "collection": "leads",
        "columns": [
            "company",
            "status",
            "score_total",
            "recommended_pricing_model",
            "quote_id",
            "draft_id",
            "why_fit",
            "evidence_url"
        ],
        "actions": []
    },
    {
        "name": "Quotes",
        "collection": "quotes",
        "columns": [
            "prospect",
            "agent_name",
            "pricing_model",
            "tier",
            "volume",
            "monthly_estimate",
            "status"
        ],
        "actions": []
    },
    {
        "name": "Outbox",
        "collection": "outbox",
        "columns": [
            "prospect",
            "to",
            "subject",
            "status",
            "lead_id"
        ],
        "actions": []
    }
]
